# Maven Wrapper configuration
# https://maven.apache.org/wrapper/
wrapperVersion=3.3.2
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.9/apache-maven-3.9.9-bin.zip
distributionSha256Sum=9e19d2fb3e8e5a5b7604f1e59c242da1ff26c7ef11c75b970e3b5e9b0e6e1e5e
