CREATE TABLE alert_runtime_state (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    state_key VARCHAR(180) NOT NULL,
    node_id BIGINT NOT NULL,
    rule_id BIGINT NULL,
    alert_type VARCHAR(32) NOT NULL,
    lifecycle_state VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    current_level VARCHAR(16) NULL,
    active_alert_id BIGINT NULL,
    occurrence_no INT NOT NULL DEFAULT 0,
    over_limit_since DATETIME(3) NULL,
    last_observed_at DATETIME(3) NULL,
    last_received_at DATETIME(3) NULL,
    last_evaluated_at DATETIME(3) NULL,
    last_triggered_at DATETIME(3) NULL,
    cooldown_until DATETIME(3) NULL,
    recovered_at DATETIME(3) NULL,
    maintenance_suppressed TINYINT(1) NOT NULL DEFAULT 0,
    shelved_until DATETIME(3) NULL,
    rule_version VARCHAR(64) NULL,
    last_source_instance_id VARCHAR(64) NULL,
    last_source_sequence BIGINT NULL,
    suppressed_count INT NOT NULL DEFAULT 0,
    optimistic_version INT NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE INDEX uk_alert_runtime_state_key (state_key),
    INDEX idx_alert_runtime_lifecycle (lifecycle_state),
    INDEX idx_alert_runtime_active_alert (active_alert_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='可恢复的告警运行状态，独立于告警历史事实';

ALTER TABLE alert_event
    ADD COLUMN occurrence_no INT NULL,
    ADD COLUMN state_key VARCHAR(180) NULL,
    ADD COLUMN rule_version VARCHAR(64) NULL,
    ADD COLUMN rule_snapshot JSON NULL,
    ADD COLUMN evidence_snapshot JSON NULL,
    ADD COLUMN data_source VARCHAR(32) NULL,
    ADD COLUMN source_instance_id VARCHAR(64) NULL,
    ADD COLUMN source_sequence BIGINT NULL,
    ADD COLUMN source_observed_at DATETIME(3) NULL,
    ADD COLUMN source_received_at DATETIME(3) NULL,
    ADD COLUMN detected_at DATETIME(3) NULL,
    ADD COLUMN persisted_at DATETIME(3) NULL,
    ADD COLUMN pushed_at DATETIME(3) NULL,
    ADD COLUMN topology_version VARCHAR(32) NULL,
    ADD COLUMN topology_simulated TINYINT(1) NULL,
    ADD COLUMN recovered_at DATETIME(3) NULL,
    ADD COLUMN previous_alert_id BIGINT NULL,
    ADD INDEX idx_alert_state_key (state_key),
    ADD INDEX idx_alert_source_observed (source_observed_at),
    ADD INDEX idx_alert_node_status_trigger (node_id, status, trigger_time);

CREATE TABLE alert_delivery_metric (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    alert_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    username VARCHAR(100) NOT NULL,
    role VARCHAR(32) NOT NULL,
    client_session_id VARCHAR(128) NULL,
    client_rendered_at DATETIME(3) NULL,
    ack_received_at DATETIME(3) NOT NULL,
    latency_ms BIGINT NULL,
    invalid_reason VARCHAR(64) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE INDEX uk_alert_delivery_user (alert_id, user_id),
    INDEX idx_alert_delivery_ack (ack_received_at),
    INDEX idx_alert_delivery_alert (alert_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='浏览器完成告警呈现的确认记录，不代表业务确认';
